# Generated by Django 5.1.5 on 2025-02-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_organizationregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
