# Generated by Django 5.1.5 on 2025-03-09 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_organization_name_remove_organization_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_register',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='home.organizationregister'),
        ),
    ]
