# Generated by Django 5.1.5 on 2025-03-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_organizationregister_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationregister',
            name='user',
        ),
    ]
