# Generated by Django 5.1.5 on 2025-02-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
    ]
