# Generated by Django 5.1.5 on 2025-03-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_organizationregister_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Unnamed Organization', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_register',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='home.organizationregister'),
        ),
    ]
