# Generated by Django 5.1.5 on 2025-02-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
    ]
