# Generated by Django 5.1.5 on 2025-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_organizationregister_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationregister',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
