# Generated by Django 5.1.5 on 2025-03-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
