# Generated by Django 5.1 on 2025-03-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_campaign_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('num_donors', models.IntegerField(default=0)),
                ('num_campaigns', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_reports', to='home.organization')),
            ],
        ),
    ]
