# Generated by Django 5.1 on 2025-03-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_charityreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharityReport',
        ),
    ]
