# Generated by Django 5.1 on 2025-03-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_charityreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
