# Generated by Django 5.1.5 on 2025-03-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_campaign_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
