# Generated by Django 5.1.5 on 2025-03-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_campaign_raised_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharityReport',
        ),
    ]
