# Generated by Django 5.1.5 on 2025-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_delete_charityreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_edit_pending',
            field=models.BooleanField(default=False),
        ),
    ]
